{
 "title": "SABD_",
 "time": { "from": "2020-11-03T15:46:27.075Z", "to": "2025-02-26T02:08:43.794Z" },
 "panels": [
  {
   "title": "Performance Query 1",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "MGET performance:Q1:sql:1 performance:Q1:sql:2 performance:Q1:sql:3 performance:Q1:sql:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q1:rdd:1 performance:Q1:rdd:2 performance:Q1:rdd:3 performance:Q1:rdd:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q1:dataframe:1 performance:Q1:dataframe:2 performance:Q1:dataframe:3 performance:Q1:dataframe:4",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Performance Query 4",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "MGET performance:Q4:silhouette:1 performance:Q4:silhouette:2 performance:Q4:silhouette:3 performance:Q4:silhouette:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q4:elbow:1 performance:Q4:elbow:2 performance:Q4:elbow:3 performance:Q4:elbow:4",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 4 Silhouette - Clustering ",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "MGET clustering:silhouette:PL clustering:silhouette:FI clustering:silhouette:SG clustering:silhouette:AT clustering:silhouette:FR clustering:silhouette:AR clustering:silhouette:NO clustering:silhouette:CN clustering:silhouette:BR clustering:silhouette:SI clustering:silhouette:SE clustering:silhouette:MX clustering:silhouette:IT clustering:silhouette:ES clustering:silhouette:KR clustering:silhouette:ZA clustering:silhouette:MA clustering:silhouette:BE clustering:silhouette:CH clustering:silhouette:CA clustering:silhouette:DE clustering:silhouette:US clustering:silhouette:AE clustering:silhouette:GB clustering:silhouette:SN clustering:silhouette:CZ clustering:silhouette:AU clustering:silhouette:TH clustering:silhouette:IE clustering:silhouette:IN",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Performance Query 3",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "MGET performance:Q3:sql:1 performance:Q3:sql:2 performance:Q3:sql:3 performance:Q3:sql:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q3:rdd:1 performance:Q3:rdd:2 performance:Q3:rdd:3 performance:Q3:rdd:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q3:dataframe:1 performance:Q3:dataframe:2 performance:Q3:dataframe:3 performance:Q3:dataframe:4",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 3 - Carbon Intensity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "MGET q3:hourly_avg:IT:01\nq3:hourly_avg:IT:02\nq3:hourly_avg:IT:03\nq3:hourly_avg:IT:04\nq3:hourly_avg:IT:05\nq3:hourly_avg:IT:06\nq3:hourly_avg:IT:07\nq3:hourly_avg:IT:08\nq3:hourly_avg:IT:09\nq3:hourly_avg:IT:10\nq3:hourly_avg:IT:11\nq3:hourly_avg:IT:12\nq3:hourly_avg:IT:13\nq3:hourly_avg:IT:14\nq3:hourly_avg:IT:15\nq3:hourly_avg:IT:16\nq3:hourly_avg:IT:17\nq3:hourly_avg:IT:18\nq3:hourly_avg:IT:19\nq3:hourly_avg:IT:20\nq3:hourly_avg:IT:21\nq3:hourly_avg:IT:22\nq3:hourly_avg:IT:23\nq3:hourly_avg:IT:00",
     "type": "cli"
    },
    {
     "query": "MGET q3:hourly_avg:SE:01\nq3:hourly_avg:SE:02\nq3:hourly_avg:SE:03\nq3:hourly_avg:SE:04\nq3:hourly_avg:SE:05\nq3:hourly_avg:SE:06\nq3:hourly_avg:SE:07\nq3:hourly_avg:SE:08\nq3:hourly_avg:SE:09\nq3:hourly_avg:SE:10\nq3:hourly_avg:SE:11\nq3:hourly_avg:SE:12\nq3:hourly_avg:SE:13\nq3:hourly_avg:SE:14\nq3:hourly_avg:SE:15\nq3:hourly_avg:SE:16\nq3:hourly_avg:SE:17\nq3:hourly_avg:SE:18\nq3:hourly_avg:SE:19\nq3:hourly_avg:SE:20\nq3:hourly_avg:SE:21\nq3:hourly_avg:SE:22\nq3:hourly_avg:SE:23\nq3:hourly_avg:SE:00",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Performance Query 2",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "MGET performance:Q2:sql:1 performance:Q2:sql:2 performance:Q2:sql:3 performance:Q2:sql:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q2:rdd:1 performance:Q2:rdd:2 performance:Q2:rdd:3 performance:Q2:rdd:4",
     "type": "cli"
    },
    {
     "query": "MGET performance:Q2:dataframe:1 performance:Q2:dataframe:2 performance:Q2:dataframe:3 performance:Q2:dataframe:4",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 2 - Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "MGET q2:italy:monthly_avg:2021_01 q2:italy:monthly_avg:2021_02 q2:italy:monthly_avg:2021_03 q2:italy:monthly_avg:2021_04 q2:italy:monthly_avg:2021_05 q2:italy:monthly_avg:2021_06 q2:italy:monthly_avg:2021_07 q2:italy:monthly_avg:2021_08 q2:italy:monthly_avg:2021_09 q2:italy:monthly_avg:2021_10 q2:italy:monthly_avg:2021_11 q2:italy:monthly_avg:2021_12 q2:italy:monthly_avg:2022_01 q2:italy:monthly_avg:2022_02 q2:italy:monthly_avg:2022_03 q2:italy:monthly_avg:2022_04 q2:italy:monthly_avg:2022_05 q2:italy:monthly_avg:2022_06 q2:italy:monthly_avg:2022_07 q2:italy:monthly_avg:2022_08 q2:italy:monthly_avg:2022_09 q2:italy:monthly_avg:2022_10 q2:italy:monthly_avg:2022_11 q2:italy:monthly_avg:2022_12 q2:italy:monthly_avg:2023_01 q2:italy:monthly_avg:2023_02 q2:italy:monthly_avg:2023_03 q2:italy:monthly_avg:2023_04 q2:italy:monthly_avg:2023_05 q2:italy:monthly_avg:2023_06 q2:italy:monthly_avg:2023_07 q2:italy:monthly_avg:2023_08 q2:italy:monthly_avg:2023_09 q2:italy:monthly_avg:2023_10 q2:italy:monthly_avg:2023_11 q2:italy:monthly_avg:2023_12 q2:italy:monthly_avg:2024_01 q2:italy:monthly_avg:2024_02 q2:italy:monthly_avg:2024_03 q2:italy:monthly_avg:2024_04 q2:italy:monthly_avg:2024_05 q2:italy:monthly_avg:2024_06 q2:italy:monthly_avg:2024_07 q2:italy:monthly_avg:2024_08 q2:italy:monthly_avg:2024_09 q2:italy:monthly_avg:2024_10 q2:italy:monthly_avg:2024_11 q2:italy:monthly_avg:2024_12 ",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Elbow Tuning Results",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "MGET elbow:2 elbow:3 elbow:4 elbow:5 elbow:6 elbow:7 elbow:8 elbow:9 elbow:10 elbow:11 elbow:12 elbow:13 elbow:14 elbow:15",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 1 - Carbon Intensity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "MGET q1:2021:IT q1:2022:IT q1:2023:IT q1:2024:IT",
     "type": "cli"
    },
    {
     "query": "MGET q1:2021:SE q1:2022:SE q1:2023:SE q1:2024:SE",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Silhouette Tuning Results",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "MGET silhouette:2 silhouette:3 silhouette:4 silhouette:5 silhouette:6 silhouette:7 silhouette:8 silhouette:9 silhouette:10 silhouette:11 silhouette:12 silhouette:13 silhouette:14 silhouette:15",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 4 Elbow - Clustering ",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "MGET clustering:elbow:PL clustering:elbow:FI clustering:elbow:SG clustering:elbow:AT clustering:elbow:FR clustering:elbow:AR clustering:elbow:NO clustering:elbow:CN clustering:elbow:BR clustering:elbow:SI clustering:elbow:SE clustering:elbow:MX clustering:elbow:IT clustering:elbow:ES clustering:elbow:KR clustering:elbow:ZA clustering:elbow:MA clustering:elbow:BE clustering:elbow:CH clustering:elbow:CA clustering:elbow:DE clustering:elbow:US clustering:elbow:AE clustering:elbow:GB clustering:elbow:SN clustering:elbow:CZ clustering:elbow:AU clustering:elbow:TH clustering:elbow:IE clustering:elbow:IN\n",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 4 Silhouette - Clustering",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "query": "MGET clustering:silhouette:PL clustering:silhouette:FI clustering:silhouette:SG clustering:silhouette:AT clustering:silhouette:FR clustering:silhouette:AR clustering:silhouette:NO clustering:silhouette:CN clustering:silhouette:BR clustering:silhouette:SI clustering:silhouette:SE clustering:silhouette:MX clustering:silhouette:IT clustering:silhouette:ES clustering:silhouette:KR clustering:silhouette:ZA clustering:silhouette:MA clustering:silhouette:BE clustering:silhouette:CH clustering:silhouette:CA clustering:silhouette:DE clustering:silhouette:US clustering:silhouette:AE clustering:silhouette:GB clustering:silhouette:SN clustering:silhouette:CZ clustering:silhouette:AU clustering:silhouette:TH clustering:silhouette:IE clustering:silhouette:IN",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 4 Elbow - Clustering",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "query": "MGET clustering:elbow:PL clustering:elbow:FI clustering:elbow:SG clustering:elbow:AT clustering:elbow:FR clustering:elbow:AR clustering:elbow:NO clustering:elbow:CN clustering:elbow:BR clustering:elbow:SI clustering:elbow:SE clustering:elbow:MX clustering:elbow:IT clustering:elbow:ES clustering:elbow:KR clustering:elbow:ZA clustering:elbow:MA clustering:elbow:BE clustering:elbow:CH clustering:elbow:CA clustering:elbow:DE clustering:elbow:US clustering:elbow:AE clustering:elbow:GB clustering:elbow:SN clustering:elbow:CZ clustering:elbow:AU clustering:elbow:TH clustering:elbow:IE clustering:elbow:IN\n",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 3 - Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "query": "MGET q3:hourly_avg:IT:01\nq3:hourly_avg:IT:02\nq3:hourly_avg:IT:03\nq3:hourly_avg:IT:04\nq3:hourly_avg:IT:05\nq3:hourly_avg:IT:06\nq3:hourly_avg:IT:07\nq3:hourly_avg:IT:08\nq3:hourly_avg:IT:09\nq3:hourly_avg:IT:10\nq3:hourly_avg:IT:11\nq3:hourly_avg:IT:12\nq3:hourly_avg:IT:13\nq3:hourly_avg:IT:14\nq3:hourly_avg:IT:15\nq3:hourly_avg:IT:16\nq3:hourly_avg:IT:17\nq3:hourly_avg:IT:18\nq3:hourly_avg:IT:19\nq3:hourly_avg:IT:20\nq3:hourly_avg:IT:21\nq3:hourly_avg:IT:22\nq3:hourly_avg:IT:23\nq3:hourly_avg:IT:00",
     "type": "cli"
    },
    {
     "query": "MGET q3:hourly_avg:SE:01\nq3:hourly_avg:SE:02\nq3:hourly_avg:SE:03\nq3:hourly_avg:SE:04\nq3:hourly_avg:SE:05\nq3:hourly_avg:SE:06\nq3:hourly_avg:SE:07\nq3:hourly_avg:SE:08\nq3:hourly_avg:SE:09\nq3:hourly_avg:SE:10\nq3:hourly_avg:SE:11\nq3:hourly_avg:SE:12\nq3:hourly_avg:SE:13\nq3:hourly_avg:SE:14\nq3:hourly_avg:SE:15\nq3:hourly_avg:SE:16\nq3:hourly_avg:SE:17\nq3:hourly_avg:SE:18\nq3:hourly_avg:SE:19\nq3:hourly_avg:SE:20\nq3:hourly_avg:SE:21\nq3:hourly_avg:SE:22\nq3:hourly_avg:SE:23\nq3:hourly_avg:SE:00",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 3 - CFE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "query": "MGET q3:hourly_avg:IT:01\nq3:hourly_avg:IT:02\nq3:hourly_avg:IT:03\nq3:hourly_avg:IT:04\nq3:hourly_avg:IT:05\nq3:hourly_avg:IT:06\nq3:hourly_avg:IT:07\nq3:hourly_avg:IT:08\nq3:hourly_avg:IT:09\nq3:hourly_avg:IT:10\nq3:hourly_avg:IT:11\nq3:hourly_avg:IT:12\nq3:hourly_avg:IT:13\nq3:hourly_avg:IT:14\nq3:hourly_avg:IT:15\nq3:hourly_avg:IT:16\nq3:hourly_avg:IT:17\nq3:hourly_avg:IT:18\nq3:hourly_avg:IT:19\nq3:hourly_avg:IT:20\nq3:hourly_avg:IT:21\nq3:hourly_avg:IT:22\nq3:hourly_avg:IT:23\nq3:hourly_avg:IT:00",
     "type": "cli"
    },
    {
     "query": "MGET q3:hourly_avg:SE:01\nq3:hourly_avg:SE:02\nq3:hourly_avg:SE:03\nq3:hourly_avg:SE:04\nq3:hourly_avg:SE:05\nq3:hourly_avg:SE:06\nq3:hourly_avg:SE:07\nq3:hourly_avg:SE:08\nq3:hourly_avg:SE:09\nq3:hourly_avg:SE:10\nq3:hourly_avg:SE:11\nq3:hourly_avg:SE:12\nq3:hourly_avg:SE:13\nq3:hourly_avg:SE:14\nq3:hourly_avg:SE:15\nq3:hourly_avg:SE:16\nq3:hourly_avg:SE:17\nq3:hourly_avg:SE:18\nq3:hourly_avg:SE:19\nq3:hourly_avg:SE:20\nq3:hourly_avg:SE:21\nq3:hourly_avg:SE:22\nq3:hourly_avg:SE:23\nq3:hourly_avg:SE:00",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 3 - CFE",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "query": "MGET q3:hourly_avg:IT:01\nq3:hourly_avg:IT:02\nq3:hourly_avg:IT:03\nq3:hourly_avg:IT:04\nq3:hourly_avg:IT:05\nq3:hourly_avg:IT:06\nq3:hourly_avg:IT:07\nq3:hourly_avg:IT:08\nq3:hourly_avg:IT:09\nq3:hourly_avg:IT:10\nq3:hourly_avg:IT:11\nq3:hourly_avg:IT:12\nq3:hourly_avg:IT:13\nq3:hourly_avg:IT:14\nq3:hourly_avg:IT:15\nq3:hourly_avg:IT:16\nq3:hourly_avg:IT:17\nq3:hourly_avg:IT:18\nq3:hourly_avg:IT:19\nq3:hourly_avg:IT:20\nq3:hourly_avg:IT:21\nq3:hourly_avg:IT:22\nq3:hourly_avg:IT:23\nq3:hourly_avg:IT:00",
     "type": "cli"
    },
    {
     "query": "MGET q3:hourly_avg:SE:01\nq3:hourly_avg:SE:02\nq3:hourly_avg:SE:03\nq3:hourly_avg:SE:04\nq3:hourly_avg:SE:05\nq3:hourly_avg:SE:06\nq3:hourly_avg:SE:07\nq3:hourly_avg:SE:08\nq3:hourly_avg:SE:09\nq3:hourly_avg:SE:10\nq3:hourly_avg:SE:11\nq3:hourly_avg:SE:12\nq3:hourly_avg:SE:13\nq3:hourly_avg:SE:14\nq3:hourly_avg:SE:15\nq3:hourly_avg:SE:16\nq3:hourly_avg:SE:17\nq3:hourly_avg:SE:18\nq3:hourly_avg:SE:19\nq3:hourly_avg:SE:20\nq3:hourly_avg:SE:21\nq3:hourly_avg:SE:22\nq3:hourly_avg:SE:23\nq3:hourly_avg:SE:00",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 2 - CFE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "query": "MGET q2:italy:monthly_avg:2021_01 q2:italy:monthly_avg:2021_02 q2:italy:monthly_avg:2021_03 q2:italy:monthly_avg:2021_04 q2:italy:monthly_avg:2021_05 q2:italy:monthly_avg:2021_06 q2:italy:monthly_avg:2021_07 q2:italy:monthly_avg:2021_08 q2:italy:monthly_avg:2021_09 q2:italy:monthly_avg:2021_10 q2:italy:monthly_avg:2021_11 q2:italy:monthly_avg:2021_12 q2:italy:monthly_avg:2022_01 q2:italy:monthly_avg:2022_02 q2:italy:monthly_avg:2022_03 q2:italy:monthly_avg:2022_04 q2:italy:monthly_avg:2022_05 q2:italy:monthly_avg:2022_06 q2:italy:monthly_avg:2022_07 q2:italy:monthly_avg:2022_08 q2:italy:monthly_avg:2022_09 q2:italy:monthly_avg:2022_10 q2:italy:monthly_avg:2022_11 q2:italy:monthly_avg:2022_12 q2:italy:monthly_avg:2023_01 q2:italy:monthly_avg:2023_02 q2:italy:monthly_avg:2023_03 q2:italy:monthly_avg:2023_04 q2:italy:monthly_avg:2023_05 q2:italy:monthly_avg:2023_06 q2:italy:monthly_avg:2023_07 q2:italy:monthly_avg:2023_08 q2:italy:monthly_avg:2023_09 q2:italy:monthly_avg:2023_10 q2:italy:monthly_avg:2023_11 q2:italy:monthly_avg:2023_12 q2:italy:monthly_avg:2024_01 q2:italy:monthly_avg:2024_02 q2:italy:monthly_avg:2024_03 q2:italy:monthly_avg:2024_04 q2:italy:monthly_avg:2024_05 q2:italy:monthly_avg:2024_06 q2:italy:monthly_avg:2024_07 q2:italy:monthly_avg:2024_08 q2:italy:monthly_avg:2024_09 q2:italy:monthly_avg:2024_10 q2:italy:monthly_avg:2024_11 q2:italy:monthly_avg:2024_12 ",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Query 1 - CFE",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "query": "MGET q1:2021:IT q1:2022:IT q1:2023:IT q1:2024:IT",
     "type": "cli"
    },
    {
     "query": "MGET q1:2021:SE q1:2022:SE q1:2023:SE q1:2024:SE",
     "type": "cli"
    }
   ]
  }
 ]
}